JPETTomography/j-pet-framework-examples

- AnalysisExample/CMakeLists.txt
- AnalysisExample/TaskA.cpp
- AnalysisExample/TaskD.cpp
- CMakeLists.txt
- LargeBarrelAnalysis/CMakeLists.txt
- LargeBarrelAnalysis/TaskA.cpp
- LargeBarrelAnalysis/TaskA.h
- LargeBarrelAnalysis/TaskB1.cpp
- LargeBarrelAnalysis/TaskB1.h
- LargeBarrelAnalysis/TaskC.cpp
- LargeBarrelAnalysis/TaskC.h
- LargeBarrelAnalysis/TaskD.cpp
- LargeBarrelAnalysis/TaskE.cpp
- LargeBarrelAnalysis/main.cpp
- ScopeAnalysis/CMakeLists.txt
- ScopeLoaderExample/CMakeLists.txt
Changes:
1. removed reinterpret_cast usages as they are no longer needed
2. removed debugging couts from AnalysisExample
3. CHanged LargeBarrelAnalysis to process all events rather than ends of time windows
4. Added sorting of hits in LargeBarrelAnalysis/TaskC
5. Update version of the framework submodule
> Minor updates of the examples

- README
Change submodule of j-pet-framework to v5.0
Change author list
> Change j-pet-framework version and author list

- LargeBarrelAnalysisExtended/HitFinderTools.cpp
- LargeBarrelAnalysisExtended/HitFinderToolsTest.cpp
Z axis position is now correctly calculated.
Tests for HitFinderTools checking if Z axis convention is held are also added.
> Fix z axis position

- CMakeLists.txt
- download_data.sh
Necessary changes at sphinx already done, everything should work better than previously.
> Smarter data downloading

- CMakeLists.txt
- VelocityCalibration/CMakeLists.txt
- VelocityCalibration/DeltaTFinder.cpp
- VelocityCalibration/DeltaTFinder.h
- VelocityCalibration/estimateVelocity.cpp
- VelocityCalibration/main.cpp
- VelocityCalibration/userParams.json
-A new module DeltaTFinder was created. This module is dedicated for measurements with collimator in different positions along z axis.
This module is looking for time difference between A and B side for each scintillator. A Gaussian function is fitted to each time difference AB (algorithm is looking for maximum bin and Gaussian function is fitted in range maximum bin +/- 2 bins). Control histograms are saved to automatically created folder Results. A txt file with fit results is also created. Slot_id, position, threshold, mean value of fitted function, error of fitted function, chi_square and NDF are saved to results.txt.
-Another, separate program (estimateVelocity.cpp) has been written to estimate effective velocity of signal inside scintillator based on file results.txt. This program …
> Velocity calibration

- .travis.yml
- TimeCalibration/CMakeLists.txt
- VelocityCalibration/DeltaTFinder.cpp
- VelocityCalibration/DeltaTFinder.h
- VelocityCalibration/README
- VelocityCalibration/main.cpp
- VelocityCalibration/run.sh
* Added missing VelocityCalibration run.sh and README files
* Adapted VelocityCalibration example to the new task scheme
* Added CMakeLists.txt file to TimeCalibration example
* Added Travis config file with rough integration tests
> Small fixes

- LargeBarrelAnalysis/EventCategorizer.cpp
- LargeBarrelAnalysis/EventFinder.cpp
- LargeBarrelAnalysis/HitFinderTools.cpp
- LargeBarrelAnalysis/SignalFinderTools.cpp
- LargeBarrelAnalysis/SignalFinderTools.h
- TimeCalibration/TimeCalibration.cpp
Remove all warnings and some refactory(tabs to space)
> Remove warnings

- LargeBarrelAnalysis/TimeWindowCreator.cpp
- LargeBarrelAnalysis/TimeWindowCreator.h
It was a nullptr so its single remaining usage was causing a segfault.
> Remove obsolete pointer and its usage

- VelocityCalibration/main.cpp
Removed in order to work with framework without db handler
> Remove DB Handler import from Velocity main

- LargeBarrelAnalysis/HitFinderTools.h
- LargeBarrelAnalysis/HitFinderToolsTest.cpp
Small RP fixing tests for HitFinderTools.
> Fix HitFinderToolsTests

- TimeCalibration/CMakeLists.txt
- VelocityCalibration/CMakeLists.txt
Fixes http://sphinx.if.uj.edu.pl/redmine/issues/918
> Remove dbconfig

- VelocityCalibration/DeltaTFinder.cpp
Similiar merge to the one on master branch
> Fix to velocity calibration develop

- LargeBarrelAnalysis/EventCategorizerTools.cpp
Described in here
[http://sphinx.if.uj.edu.pl/redmine/issues/955](Redmine)
> Fix of const values in EvCatTool

- .gitmodules
- CMakeLists.txt
> Add j-pet-mlem as submodule

- .travis.yml
Cleans up travis.yml file from unused libraries and change to make all targets at start.
> Cleanup travis.yml

- .gitmodules
- ImageReconstruction/main.cpp
- LargeBarrelAnalysis/main.cpp
- NewAnalysisTemplate/main.cpp
- ScopeAnalysis/main.cpp
- ScopeLoaderExample/main.cpp
- TimeCalibration/main.cpp
- VelocityCalibration/main.cpp
Also, update the j-pet-framework version and fix small typo in .gitmodules
This is the fixed code of #94 and should be merged instead of the previous PR.
> Add the try catch in main.cpp of every examples

- .gitmodules
- CMakeLists.txt
- ImageReconstruction/main.cpp
- LargeBarrelAnalysis/HitFinder.cpp
- LargeBarrelAnalysis/HitFinderTools.cpp
- LargeBarrelAnalysis/TimeWindowCreator.cpp
- LargeBarrelAnalysis/main.cpp
- NewAnalysisTemplate/main.cpp
- ScopeAnalysis/main.cpp
- ScopeLoaderExample/main.cpp
- TimeCalibration/main.cpp
- VelocityCalibration/DeltaTFinder.cpp
- VelocityCalibration/main.cpp
Fix some code to remove compilation errors. That should not affect the logic.
Also, turn off warning flags for mlem submodule.
It should be merged after #97
> Warnings corrections

- CMakeLists.txt
- MCGeantAnalysis/CMakeLists.txt
- MCGeantAnalysis/README
- MCGeantAnalysis/main.cpp
- MCGeantAnalysis/run.sh
- NewAnalysisTemplate/CMakeLists.txt
- TimeCalibration/CMakeLists.txt
This PR may only be accepted after PR #181 to core framework.
Redundant files were removed and the example is now as simple as possible.
> MC wrapper PR after a cleanup (replaces PR #87)

- CMakeLists.txt
- InterThresholdCalibration/CMakeLists.txt
- InterThresholdCalibration/InterThresholdCalibration.cpp
- InterThresholdCalibration/InterThresholdCalibration.h
- InterThresholdCalibration/README
- InterThresholdCalibration/main.cpp
All remarks from https://github.com/JPETTomography/j-pet-framework-examples/pull/85 are done.
This is a separate PR as I cannot push to Magdas branch.
> Interthreshold calib 

- CosmicAnalysis/EventCategorizerCosmic.cpp
- CosmicAnalysis/EventCategorizerCosmic.h
- CosmicAnalysis/PARAMETERS
- CosmicAnalysis/main.cpp
- Imaging/EventCategorizerImaging.cpp
- Imaging/EventCategorizerImaging.h
- Imaging/PARAMETERS
- Imaging/main.cpp
- LargeBarrelAnalysis/EventCategorizer.cpp
- LargeBarrelAnalysis/EventCategorizerTools.cpp
- LargeBarrelAnalysis/EventCategorizerTools.h
- LargeBarrelAnalysis/EventCategorizerToolsTest.cpp
- PhysicAnalysis/EventCategorizerPhysics.cpp
- PhysicAnalysis/EventCategorizerPhysics.h
- PhysicAnalysis/PARAMETERS
- PhysicAnalysis/main.cpp
- renaming of two methods used for streaming
- correcting names and definitions of the histograms
- removing unused argument in one of the streaming methods
- unification of the units - all  methods return in [ps], only in some histograms are filled with [ns]
- adding description of the parameters for streaming
- adding tests for streaming methods
> Streaming improvements

- ImageReconstruction/MLEMRunner.cpp
- ImageReconstruction/MLEMRunner.h
Update j-pet-mlem submodule and export TOF sigma to user param
> Update j-pet-mlem submodule and export TOF sigma to user param

- CosmicAnalysis/README.md
- Imaging/README.md
- LargeBarrelAnalysis/PARAMETERS.md
- LargeBarrelAnalysis/README.md
- LargeBarrelAnalysis/SignalTransformer.cpp
- LargeBarrelAnalysis/run.sh
- PhysicAnalysis/README.md
PR includes small corrections, requested on Redmine - more details in Readmes etc.
> Prerelease corrections

- MCGeantAnalysis/CMakeLists.txt
- MCGeantAnalysis/PARAMETERS.md
- MCGeantAnalysis/README.md
- MCGeantAnalysis/run.sh
Small changes in MCGeant Analysis
- added parameters description 
- remove logs cleaning
>  MCGeantAnalysis : add params description

- LargeBarrelAnalysis/EventCategorizerTools.cpp
- LargeBarrelAnalysis/EventCategorizerTools.h
- LargeBarrelAnalysis/EventCategorizerToolsTest.cpp
By adding missing 1/2 factor. Also, refactoring of
calculateAnihilationPoints.
Some tests are commented, and must be checked and extended.
> Change definition of calculateTOF method

- ScopeLoaderExample/README.md
More info on readme file for the example. 
http://sphinx.if.uj.edu.pl/redmine/issues/1086
> More describtion in README

- LargeBarrelAnalysis/SignalFinder.cpp
- LargeBarrelAnalysis/SignalFinder.h
- LargeBarrelAnalysis/SignalFinderTools.cpp
- LargeBarrelAnalysis/SignalFinderTools.h
- LargeBarrelAnalysis/SignalFinderToolsTest.cpp
- LargeBarrelAnalysis/TimeWindowCreator.h
This functionality should have entered version 7.0 and we need to incorporate it into master quickly.
The strategy to realize it is discussed at Redmine issue no. 1111:
http://sphinx.if.uj.edu.pl/redmine/issues/1111
> Hotfix: add optional ordering of thresholds by values

- LargeBarrelAnalysis/ToTConverter.cpp
- LargeBarrelAnalysis/ToTConverter.h
- LargeBarrelAnalysis/ToTConverterTest.cpp
Add ToT to Edep converter with a kind of lookup table.
Some tests are added but not full list.
This PR should be accepted after JPetCachedFunction PR from j-pet-framework core.
> ToT to Edep general converter

- InterThresholdCalibration/CMakeLists.txt
- InterThresholdCalibration/PARAMETERS.md
At last documentation is done. Userparams file is also submitted to the sphinx.
> Add parameters file to interthreshold calib example

- LargeBarrelAnalysis/HitFinder.cpp
- LargeBarrelAnalysis/HitFinderTools.cpp
- LargeBarrelAnalysis/SignalFinder.cpp
- LargeBarrelAnalysis/SignalFinder.h
- LargeBarrelAnalysis/SignalFinderTools.cpp
- LargeBarrelAnalysis/SignalFinderTools.h
- LargeBarrelAnalysis/SignalFinderToolsTest.cpp
- LargeBarrelAnalysis/TimeWindowCreatorTools.cpp
- LargeBarrelAnalysis/TimeWindowCreatorToolsTest.cpp
- revision of test in LargeBarrelAnalysis after other PRs 
- small correction in LLT flagging, so it works with the tests
- refactor of one variable name, so it follows convention
- small correction and addition in histogram in HitFinder
> LBA Tests check and fix

- ImageReconstruction/tests/CMakeLists.txt
- LargeBarrelAnalysis/tests/CMakeLists.txt
Fix running tests for certain boost versions
> Fix running tests for certain boost versions

- LargeBarrelAnalysis/EventCategorizer.cpp
- LargeBarrelAnalysis/EventCategorizer.h
- LargeBarrelAnalysis/EventCategorizerTools.cpp
- LargeBarrelAnalysis/EventCategorizerTools.h
- LargeBarrelAnalysis/EventFinder.cpp
- LargeBarrelAnalysis/EventFinder.h
- LargeBarrelAnalysis/HitFinder.cpp
- LargeBarrelAnalysis/HitFinder.h
- LargeBarrelAnalysis/HitFinderTools.cpp
- LargeBarrelAnalysis/HitFinderTools.h
- LargeBarrelAnalysis/SignalFinder.cpp
- LargeBarrelAnalysis/SignalFinder.h
- LargeBarrelAnalysis/SignalFinderTools.cpp
- LargeBarrelAnalysis/SignalFinderTools.h
- LargeBarrelAnalysis/SignalTransformer.cpp
- LargeBarrelAnalysis/SignalTransformer.h
- LargeBarrelAnalysis/TimeWindowCreator.cpp
- LargeBarrelAnalysis/TimeWindowCreator.h
- LargeBarrelAnalysis/TimeWindowCreatorTools.cpp
- LargeBarrelAnalysis/TimeWindowCreatorTools.h
- LargeBarrelAnalysis/main.cpp
I have incorporated new methods of creating and filling histograms for LargeBarrelAnalysis.
I would improve it later if PR for creating histograms with custom axes will be accepted. The histograms that needs this improvement are those that setting custom labels for bins as:
Corrupted, Not Corrupted, ...
Lead thr1, Trail thr1, ...
> Incorporating new method of creating an filling histograms

- LargeBarrelAnalysis/EventCategorizerTools.cpp
- LargeBarrelAnalysis/EventCategorizerTools.h
- LargeBarrelAnalysis/tests/EventCategorizerToolsTest.cpp
Following http://sphinx.if.uj.edu.pl/redmine/issues/1349
TOT calculations corrected if some threshold are missing.
> TOT calculations - correction to consider missing thresholds

- .github/workflows/ci-workflow.yml
- jenkins/Jenkinsfile
- jenkins/root_6_matrix/docker-entrypoint.sh
> Add jenkinsfile

- CMakeLists.txt
- InterfileReconstruction/CMakeLists.txt
- InterfileReconstruction/InterfileMLPReconstruction.cpp
- InterfileReconstruction/InterfileMLPReconstruction.h
- InterfileReconstruction/InterfileReconstructionTools.cpp
- InterfileReconstruction/InterfileReconstructionTools.h
- InterfileReconstruction/main.cpp
This is cherry-picked commits from modular3 branch with MLP reconstruction method.
> Add MLP method to modular4 branch

- .github/workflows/ci-workflow.yml
Ubuntu 16.04 is no longer supported by github.
> Change ubuntu 16.04 to 20.04

- ImageReconstruction/CMakeLists.txt
- ImageReconstruction/JPetGojaParser.cpp
- ImageReconstruction/JPetGojaParser.h
- ImageReconstruction/main.cpp
This PR adds JPetGojaParser that parses GOJA file and converts it to the JPetHit.
Signed-off-by: Kamil Rakoczy <kamilrakoczy1@gmail.com>
> Add JPetGojaParser
